name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permissions to the GITHUB_TOKEN
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File
        run: |
          echo "Last update: $(date)" >> update.txt

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit: $(date)"
