name: Custom Auto Commit & Issue Creator

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (4 times a day)
  workflow_dispatch:  # Allows manual execution

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permissions to the GITHUB_TOKEN
      issues: write  # Grants permission to create issues
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI  # ✅ Ensures `gh` is installed
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Set Variables
        run: |
          DAY_OF_WEEK=$(date +%u)  # Get current day of the week (1=Monday, 7=Sunday)
          RANDOM_DARK_DAYS=($(shuf -i 1-7 -n 3))  # Pick 3 random days for dark commits
          
          # Check if today is one of the dark commit days
          DARK_MODE=false
          for DARK_DAY in "${RANDOM_DARK_DAYS[@]}"; do
            if [ $DAY_OF_WEEK -eq $DARK_DAY ]; then
              DARK_MODE=true
              break
            fi
          done
          
          echo "DARK_MODE=$DARK_MODE" >> $GITHUB_ENV

      - name: Set Git Identity  # ✅ Fixes "Author identity unknown" error
        run: |
          git config --global user.email "heni.fakhr@gmail.com"
          git config --global user.name "Hengameh001"

      - name: Generate Commits (Custom Messages)
        run: |
          # Custom commit names
          COMMIT_MESSAGES=("Daily update" "Keeping the streak" "Another contribution" "Adding value to GitHub")
          RANDOM_COMMIT=${COMMIT_MESSAGES[$RANDOM % ${#COMMIT_MESSAGES[@]}]}

          # Ensure 4 commits every day (1 per run)
          for i in {1..4}; do
            echo "$RANDOM_COMMIT - $(date)" >> update.txt
            git add update.txt
            git commit -m "$RANDOM_COMMIT - $(date)"
          done

          # If today is a "dark commit" day, add 3-6 extra commits
          if [ "$DARK_MODE" = "true" ]; then
            EXTRA_COMMITS=$((RANDOM % 4 + 3))  # Random 3 to 6 extra commits
            for i in $(seq 1 $EXTRA_COMMITS); do
              RANDOM_COMMIT=${COMMIT_MESSAGES[$RANDOM % ${#COMMIT_MESSAGES[@]}]}
              echo "$RANDOM_COMMIT (Extra) - $(date)" >> update.txt
              git add update.txt
              git commit -m "$RANDOM_COMMIT (Extra) - $(date)"
            done
          fi

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Commit: $(date)"

      - name: Auto Create GitHub Issue (Custom Titles)  # ✅ FIXED: Removed unnecessary login step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Custom issue titles
          ISSUE_TITLES=("Routine GitHub Issue" "Daily GitHub Activity" "Tracking Contributions" "Staying Active")
          RANDOM_ISSUE_TITLE=${ISSUE_TITLES[$RANDOM % ${#ISSUE_TITLES[@]}]}

          gh issue create --repo $GITHUB_REPOSITORY --title "$RANDOM_ISSUE_TITLE - $(date)" --body " "
